version: '3.7'
services:
  web:
    build: ./client
    image: melloweb:v2
    restart: always
    environment:
      - API_HOST=http://api:8000
    ports:
      - '8001:80'
    depends_on:
      - api

  api:
    build: .
    image: mello:v2
    restart: always
    environment:
      - DB_URI=mongodb://db/mello
    ports:
      - '8000:8000'
    depends_on:
      - db

  db:
    image: mongo
    restart: always
    ports:
      - '27018:27017'
    volumes:
      - type: bind
        source: /Users/Nicholas/docker/volumes/mellomongo
        target: /data/db
