version: '3.7'
services:
  web:
    image: repo.treescale.com/nicholascannon1/mello/mello-web:latest
    restart: always
    labels:
      # Traefik config
      - traefik.http.routers.web.rule=Host(`mello.niccannon.com`)
      - traefik.enabled=true
    depends_on:
      - api

  api:
    image: repo.treescale.com/nicholascannon1/mello/mello-api:latest
    restart: always
    labels:
      # Traefik config
      - traefik.http.routers.web.rule=Host(`api.mello.niccannon.com`)
      - traefik.enabled=true
    env_file: .env
    networks:
      db_net: {}

networks:
  db_net:
    external: true
    name: mongodb-network
